05-29 16:59:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:191)
	at com.thebrain.common.b.y.A(qmf:122)
	at com.thebrain.common.b.y.A(qmf:59)
	at com.thebrain.common.b.y.A(qmf:38)
	at com.thebrain.personal.a.a.t.K(lld:636)
	at com.thebrain.c.e.z.L(ygg:452)
	at com.thebrain.personal.a.a.k.B(whd:369)
	at com.thebrain.personal.view.si.A(mcd:3860)
	at com.thebrain.personal.view.si.B(mcd:5238)
	at com.thebrain.personal.view.si.A(mcd:5760)
	at com.thebrain.personal.view.kc.run(mcd:2401)
	at java.lang.Thread.run(Unknown Source)
05-29 17:04:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:191)
	at com.thebrain.common.b.y.A(qmf:122)
	at com.thebrain.common.b.y.A(qmf:59)
	at com.thebrain.common.b.y.A(qmf:38)
	at com.thebrain.personal.a.a.t.K(lld:636)
	at com.thebrain.c.e.z.L(ygg:452)
	at com.thebrain.personal.a.a.k.B(whd:369)
	at com.thebrain.personal.view.si.A(mcd:3860)
	at com.thebrain.personal.view.si.B(mcd:5238)
	at com.thebrain.personal.view.si.A(mcd:5760)
	at com.thebrain.personal.view.kc.run(mcd:2401)
	at java.lang.Thread.run(Unknown Source)
06-03 17:19:12 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:191)
	at com.thebrain.common.b.y.A(qmf:122)
	at com.thebrain.common.b.y.A(qmf:59)
	at com.thebrain.common.b.y.A(qmf:38)
	at com.thebrain.personal.a.a.t.K(lld:636)
	at com.thebrain.c.e.z.L(ygg:452)
	at com.thebrain.personal.a.a.k.B(whd:369)
	at com.thebrain.personal.view.si.A(mcd:3860)
	at com.thebrain.personal.h.u.A(pod:1604)
	at com.thebrain.personal.view.ri.run(mcd:2040)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.thebrain.personal.b.d.x.dispatchEvent(yad:187)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
